// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterAPI.Models;

namespace ShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210825210700_UserModels")]
    partial class UserModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShelterAPI.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Coloring");

                    b.Property<string>("Description");

                    b.Property<bool>("IsFemale");

                    b.Property<string>("Name");

                    b.Property<double>("WeightKilo");

                    b.HasKey("CatId");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("ShelterAPI.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Breed");

                    b.Property<string>("Coloring");

                    b.Property<string>("Description");

                    b.Property<bool>("IsFemale");

                    b.Property<string>("Name");

                    b.Property<double>("WeightKilo");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("ShelterAPI.Models.UserModel", b =>
                {
                    b.Property<int>("UserModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserModelId");

                    b.ToTable("UserModels");
                });
#pragma warning restore 612, 618
        }
    }
}
